export const races = [
  'American Indian or Alaska Native',
  'Asian',
  'Black or African American',
  'Native Hawaiian or Other Pacific Islander',
  'White',
  'Saiyan',
  'Amanto',
  'Asgardian',
  'Elf',
  'Dwarf',
  'Argonian',
  'Khajiit',
  'Dragon',
  'Eldian',
  'Marleyan',
  'Frost Giant',
  'Ninken',
  'Stand',
  'Anti-Spiral',
  'Homonculus',
  'Android',
  'Squirrel',
  'Other',
];

export const genders = ['Female', 'Male', 'Other'];

export const diets = [
  'Vegetarian',
  'Gluten Free',
  'Vegan',
  'Lactose Intolerant',
  'Kosher',
  'Halal',
  'Diabetic',
  'Allergic to Peanuts',
  'Allergic to Shellfish',
  'Lactose Only',
  'Carnivore',
  'Intermittent Fasting and Will Not Shut Up About It',
  'No Solid Foods',
  'Afraid of Mushrooms',
  'No Food',
  'Soul Food Only',
  'Extra Helpings',
  'Grass Only',
  'Protein Deficiency',
  'Life Essence Only',
  'Pescatarian',
  'Flexitarian',
  'Other',
];
